### Beta distribution

[Continuous Distributions: Beta and Dirichlet Distributions (Youtube)](https://youtu.be/CEVELIz4WXM?si=3vzpeibZHCdCTRs0)\
[102C Lesson 1-2 Beta-Binomial model (Lecture 1)(Youtube)](https://youtu.be/TrO4ANmlzDg?si=W3QmGzyTwubc404G)


$$
\text{Beta}:\text{Binomial} = \text{Dirichlet}:\text{Multinomial}
$$

- Useful distribution for modeling percentages and proportions.\
(Unlike a normal distribution, the Beta distribution (PDF) is over the interval $[0,1]$ which allows a probability like value.)
- The density is proportional to $x^{\alpha-1}(1-x)^{\beta-1}$, related to Bernoulli distribution: $x^{\theta}(1-x)^{1-\theta}$.\
Bernoulli distribution allows discrete $0$ and $1$, Beta distrubution allows continuous values between $[0,1]$.

In [ ]:
import numpy as np
from scipy.stats import beta
import matplotlib.pyplot as plt

from ipywidgets import interactive
import matplotlib.pyplot as plt
import numpy as np

def beta_plot(a=.1, b=.1):
    x = np.linspace(0, 1, 101)

    fig, ax = plt.subplots(1, 2, figsize=(12,6))
    alphas = [.5, 5, 1, 2, 2]
    betas  = [.5, 1, 3, 2, 5]
    for _a, _b in zip(alphas, betas):
        ax[0].plot(x, beta.pdf(x, a=_a, b=_b), label=rf"$\alpha={_a}, \beta={_b}$")
    ax[0].legend()
    ax[0].set_xlim([0,1])
    ax[0].set_ylim([0,4])

    ax[1].plot(x, beta.pdf(x, a=a, b=b), label=rf"$\alpha={a}, \beta={b}$")
    ax[1].legend()
    ax[1].set_xlim([0,1])
    ax[1].set_ylim([0,4])
    plt.show()

interactive(beta_plot, a=(.1, 10, .1), b=(.1, 10, .1))

$$
\begin{align}
f(x;\alpha, \beta)
&= C \cdot x^{\alpha - 1} (1-x)^{\beta - 1} \\
&= \dfrac{x^{\alpha - 1} (1-x)^{\beta - 1}}{\int_0^1 u^{\alpha - 1} (1-u)^{\beta - 1} du} \\
&= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)} x^{\alpha - 1} (1-x)^{\beta - 1} \\
&= \frac{1}{\mathrm B(\alpha, \beta)} x^{\alpha - 1} (1-x)^{\beta - 1} \\
\end{align}
$$

$$
\Gamma(x) = (x-1)!
$$

- $E[X] = \dfrac{\alpha}{\alpha + \beta}$
- $0 \leq x \leq 1$
- $\alpha > 0$
- $\beta > 0$

Distribution is symmetric when $\alpha = \beta$.

The normalizing constant $\mathrm{B}(\alpha, \beta)$ is closely related to $n \choose k$.\
Let's start by deriving a gamma function $\Gamma(z)$

### Gamma funciton
Gamma function is used to extend the concept of a factorial function.

[ONE NEAT PROOF! Deriving the EULER DEFINITION of the Gamma Function! (Youtube)](https://youtu.be/2GqqEXMPMlE?si=JWHwI0RFhO-3ZPkT)\
[102C Lesson 1-2 Beta-Binomial model (Lecture 1) (Youtube)](https://youtu.be/TrO4ANmlzDg?si=TyREbiUvPTK9v48T)

<img src="https://upload.wikimedia.org/wikipedia/commons/2/2b/Generalized_factorial_function_more_infos.svg" height="400px" />

Euler's definition

$$
\begin{align*}
\Gamma(n) &= (n-1)! \quad (n \in \N) \\
\Gamma(z) &= (z-1)! \quad (z \in \R^+) \\
% &= \frac{z!}{z} \\
% &= \frac{1 \cdot 2 \cdots z}{z} \\
&= \frac{\overbrace{1 \cdot 2 \cdots (z-1) z}^{z} \overbrace{(z+1) (z+2) \cdots (z+n)}^{n}}{z (z+1) (z+2) \cdots (z+n)} \qquad \text{where,}\ z \ll n \\
&= \frac{\overbrace{1 \cdot 2 \cdots z \cdots (n-1) n}^{n} \overbrace{(n+1)(n+2) \cdots (n+z)}^{z}}{z (z+1) (z+2) \cdots (z+n)} \\
&= \frac{n!}{z} \cdot \frac{\overbrace{(n+1)(n+2) \cdots (n+z)}^{z}}{\underbrace{(z+1) (z+2) \cdots (z+n)}_{n}} \\
&= \frac{n!}{z} \cdot \frac{n^z \left( 1+\dfrac{1}{n} \right) \left( 1+\dfrac{2}{n} \right) \cdots \left( 1+\dfrac{z}{n} \right)}{n! \left( \dfrac{z+1}{1} \right) \left( \dfrac{z+2}{2} \right) \cdots \left( \dfrac{z+n}{n} \right)} \\
&= \frac{1}{z} \cdot \frac{n^z \left( 1+\dfrac{1}{n} \right) \left( 1+\dfrac{2}{n} \right) \cdots \left( 1+\dfrac{z}{n} \right)}{\left( \dfrac{z+1}{1} \right) \left( \dfrac{z+2}{2} \right) \cdots \left( \dfrac{z+n}{n} \right)} \quad \text{where,}\ n! \neq 0 \ \\
\\

\lim_{n \to \infty} n
&= \lim_{n \to \infty} \left( \frac{2}{1} \cdot \frac{3}{2} \cdot \frac{4}{3} \cdots \frac{n+1}{n} \right) \\
&= \prod_{n=1}^{\infty} \left( \frac{n+1}{n} \right) \\
&= \prod_{n=1}^{\infty} \left( 1 + \frac{1}{n} \right) \\

\lim_{n \to \infty} n^z
&= \prod_{n=1}^{\infty} \left( 1 + \frac{1}{n} \right)^{z} \\
\\
\lim_{n \to \infty} \left( 1+\dfrac{1}{n} \right) \left( 1+\dfrac{2}{n} \right) \cdots \left( 1+\dfrac{z}{n} \right)
&= 1 \\
\\

\lim_{n \to \infty} \left( \dfrac{z+1}{1} \right) \left( \dfrac{z+2}{2} \right) \cdots \left( \dfrac{z+n}{n} \right)
&= \lim_{n \to \infty} \left( 1+\dfrac{z}{1} \right) \left( 1+\dfrac{z}{2} \right) \cdots \left( 1+\dfrac{z}{n} \right) \\
&= \prod_{n=1}^{\infty} \left( 1 + \frac{z}{n} \right) \\
\\

\therefore \Gamma(z) &= \frac{1}{z} \prod_{n=1}^{\infty} \frac{\left( 1 + \dfrac{1}{n} \right)^z}{1 + \dfrac{z}{n}} = \int_{0}^{\infty} t^{z-1} e^{-t} dt

\end{align*}
$$

$$
\frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)} = {\alpha + \beta - 2 \choose \alpha - 1} \cdot (\alpha + \beta - 1) \\
$$

$$
$$

$$
\begin{align*}
f(x; \alpha, \beta)
&= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)} x^{\alpha - 1} (1-x)^{\beta - 1} \\

f(x; \alpha+1, \beta+1)
&= \frac{\Gamma(\alpha + \beta + 2)}{\Gamma(\alpha+1) \Gamma(\beta+1)} x^{\alpha} (1-x)^{\beta} \\
&= (\alpha + \beta + 1) \frac{(\alpha + \beta)!}{\alpha!\ \beta!} x^{\alpha} (1-x)^{\beta} \\
&= (\alpha + \beta + 1) {\alpha + \beta \choose \alpha} x^{\alpha} (1-x)^{\beta}
\end{align*}
$$

### Bernoulli + Binomial + Beta

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import binom, beta
from ipywidgets import interactive
import math

def plot(n=10, p=0.6):
    k = round(n*p)

    fig, ax = plt.subplots(1, 4, figsize=(24, 6))
    ax[0].set_title(rf'$Bernoulli(x;p={p})$')
    X = np.arange(0,2)
    ax[0].stem(X,[1-p,p])
    ax[0].set_ylim(0,1)
    ax[0].set_xticks(X)
    ax[0].set_xlabel(r'$X$')

    ax[1].set_title(rf'$Binomial(x;n={n},p={p})$')
    X = np.arange(0,n+1)
    ax[1].stem(X, binom.pmf(X,n,p))
    ax[1].set_ylim(0)
    ax[1].set_xticks(X)
    ax[1].set_xlabel(r'$X$')

    ax[2].set_title(rf'$Beta(x;\alpha={k+1},\beta={n-k+1})$')
    X = np.linspace(0,1,201)
    ax[2].plot(X, beta.pdf(X,a=k+1,b=n-k+1))
    ax[2].stem(k/n, beta.pdf(k/n,a=k+1,b=n-k+1), linefmt=':', markerfmt='')
    ax[2].set_xlim(0,1)
    ax[2].set_ylim(0)
    ax[2].set_xlabel(r'$X$')

    X = np.linspace(0,1,201)
    ax[3].plot(X, beta.pdf(X,a=k,b=n-k+1), label=rf"$Beta(x;\alpha={k},\beta={n-k+1})$", ls=':')
    ax[3].plot(X, beta.pdf(X,a=k+1,b=n-k+1), label=rf"$Beta(x;\alpha={k+1},\beta={n-k+1})$")
    ax[3].plot(X, beta.pdf(X,a=k+1,b=n-k), label=rf"$Beta(x;\alpha={k+1},\beta={n-k})$", ls=':')
    alpha = 0.05
    lo = beta.ppf(  alpha/2, k, n-k+1)
    hi = beta.ppf(1-alpha/2, k+1, n-k)
    lo = 0 if math.isnan(lo) else lo
    hi = 1 if math.isnan(hi) else hi
    if lo != 0:
        ax[3].stem(lo, beta.pdf(lo,a=k,b=n-k+1), linefmt=':')
    if hi != 1:
        ax[3].stem(hi, beta.pdf(hi,a=k+1,b=n-k), linefmt=':')
    ax[3].set_title(f'Clopper-Pearson interval [{lo:.3f}-{hi:.3f}]')
    ax[3].set_xlim(0,1)
    ax[3].set_ylim(0)
    ax[3].legend()
    ax[3].set_xlabel(r'$X$')

    plt.show()

interactive(plot, n=(1,40,1), p=(0,1,0.01))

### Bayes' Rule

$$
\mathrm{Pr}(\theta|\mathbf x) = \frac{\mathrm{Pr}(\mathbf x|\theta)\mathrm{Pr}(\theta)}{\mathrm{Pr}(\mathbf x)}
$$

- Posterior: $\mathrm{Pr}(\theta|\mathbf x)$ is the probability distribution that we want to find.
- Likelihood: $\mathrm{Pr}(\mathbf x|\theta)$ is the probability of observed data for a given value of $\theta$.
- Prior: $\mathrm{Pr}(\theta)$ is prior probability distribution of $\theta$.
- Marginal probability: $\mathrm{Pr}(\mathbf x)$ is the probability of observing the values in our data regardless of the value $\theta$. This is equal to the intergral of the numerator across all possible values of $\theta$. This is a constant.

Because the marginal probability $\mathrm{Pr}(\mathbf x)$ is a constant, the posterior distribution of $\theta$ is proportional to the likelihood function times the prior distribution.

$$
\mathrm{Pr}(\theta|\mathbf x) \propto \mathrm{Pr}(\mathbf x|\theta)\mathrm{Pr}(\theta)
$$


In [95]:
import numpy as np
import pandas as pd

words = ["meeing", "due", "thanks", "hello", "cool"]
df = pd.DataFrame(data={
    "cool"      : [1,1,0,1,1,0],
    "hello"     : [1,0,1,1,0,0],
    "thanks"    : [0,0,1,1,1,0],
    "due"       : [0,0,1,1,1,1],
    "meeting"   : [0,0,0,0,1,1],
    "spam label": [1,1,1,0,0,0],
})

X = df.iloc[:,:-1].to_numpy()
y = df.iloc[:, -1].to_numpy()
X, y

(array([[1, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 1, 1, 1],
        [0, 0, 0, 1, 1]]),
 array([1, 1, 1, 0, 0, 0]))

In [125]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def BCELoss(y_pred, y_true):
    return -(y_true @ np.log(y_pred).T + (1-y_true) @ np.log(1-y_pred).T) / len(y_true)

w = np.random.randn(1,5) * 0.01
b = np.zeros((1,1))

z = w@X.T + b
a = sigmoid(z)

BCELoss(a, y)

array([0.69508143])

In [165]:
import torch

x = torch.randn(1)
print(x)
print(x.softmax(0))

x.exp() / x.exp().sum()

tensor([0.3766])
tensor([1.])


tensor([1.])

In [121]:
import numpy as np
from scipy.stats import beta

# One-hot encoding for spam and ham emails with a small vocabulary
# Let's assume a vocabulary of 5 words: "free", "win", "offer", "hello", "click"
# A one-hot vector [1, 0, 0, 0, 1] would mean the message contains "free" and "click"

# Sample one-hot encoded messages
spam_emails = np.array([
    [1, 1, 0, 0, 0],  # Spam message containing "free" and "win"
    [1, 0, 1, 0, 0],  # Spam message containing "free" and "offer"
    [0, 1, 1, 0, 0]   # Spam message containing "win" and "offer"
])

ham_emails = np.array([
    [0, 0, 0, 1, 1],  # Ham message containing "hello" and "click"
    [0, 0, 0, 1, 0],  # Ham message containing "hello"
    [0, 0, 0, 0, 1]   # Ham message containing "click"
])

# We will perform Bayesian updates on the word "free"
# Let's define some priors based on our belief before seeing the data
# Prior belief: probability that any email containing "free" is spam
prior_alpha = 2  # Prior number of successes (alpha) - somewhat believe it's spam
prior_beta = 2   # Prior number of failures (beta) - somewhat believe it's not spam

# Count the number of spam emails containing the word "free"
spam_word_count = np.sum(spam_emails[:, 0])  # Count in the first column for "free"
print(spam_word_count)

# Total emails containing the word "free"
total_emails_with_word = np.sum(spam_emails[:, 0]) + np.sum(ham_emails[:, 0])
print(total_emails_with_word)

# Perform Bayesian update with the counts
posterior_alpha = prior_alpha + spam_word_count
posterior_beta = prior_beta + (total_emails_with_word - spam_word_count)
print(posterior_alpha, posterior_beta)

# Create a beta distribution with the updated alpha and beta
posterior_distribution = beta(posterior_alpha, posterior_beta)

# Now let's print out our prior and posterior beliefs
prior_distribution = beta(prior_alpha, prior_beta)

prior_mean = prior_distribution.mean()
posterior_mean = posterior_distribution.mean()

prior_mean, posterior_mean


2
2
4 2


(0.5, 0.6666666666666666)